version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    networks:
      - network
    ports:
      - ${REDIS_PORT}:6379
    volumes:
     - cache:/data
      # - ./config/redis.conf:/redis.conf
    # command: [ "redis-server", "/redis.conf" ]
    command: redis-server --save 20 1 --loglevel warning

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: unless-stopped
    depends_on:
      - redis
    networks:
      - network
    volumes:
      - ./api:/workspace
    ports:
      - ${API_PORT}:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

volumes:
  cache:
    driver: local

networks:
  network:
    driver: bridge