version: "3.8"

services:
  redis:
    image: redislabs/redistimeseries:1.10.11
    container_name: redis
    restart: unless-stopped
    networks:
      - network
    ports:
      - ${REDIS_PORT}:6379
    volumes:
      - cache:/data
      - ./config/redis.conf:/etc/redis/redis.conf
    command:  ["--loadmodule", "/usr/lib/redis/modules/redistimeseries.so", "UNLOAD", "timeseries", "/etc/redis/redis.conf"]

  api:
    build: 
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - redis
    networks:
      - network
    volumes:
      - ./api:/workspace
    ports:
      - ${API_PORT}:80
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - API_LOGGING_LEVEL=${API_PRODUCTION_LEVEL}
    command: uvicorn app.main:app --host 0.0.0.0 --port 80 --reload

volumes:
  cache:
    driver: local

networks:
  network:
    driver: bridge