FROM python:3.10 AS base

# Create a user and group named 'vscode'
RUN groupadd -r vscode && useradd -m -r -g vscode vscode

# Set the working directory and user
WORKDIR /app
USER vscode

# install popular Python packages
COPY requirements.txt ../requirements.txt
RUN pip3 install -r ../requirements.txt

EXPOSE 80

# Install debugger
RUN pip install debugpy

ENTRYPOINT [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m"]