FROM python:3.10 AS base

# Create a user and group named 'vscode'
RUN groupadd -r vscode && useradd -m -r -g vscode vscode

# Set the working directory and user
WORKDIR /workspace
USER vscode

# install Python packages
COPY requirements.txt ./requirements.txt
COPY requirements-dev.txt ./requirements-dev.txt
RUN pip3 install -r ./requirements.txt -r ./requirements-dev.txt

EXPOSE 80

ENTRYPOINT [ "python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "--wait-for-client", "-m"]